import turtle
wn = turtle.Screen()
alex = turtle.Turtle()
sandra = turtle.Turtle()
alex.color("red")
sandra.color("blue")

alex.forward(50)
sandra.backward(50)
alex.left(90)
sandra.right(90)
alex.forward(30)
sandra.backward(30)
alex.right(60)
sandra.left(60)
alex.forward(200)
sandra.backward(200)
alex.left(90)
sandra.right(90)
alex.forward(50)
sandra.backward(50)
alex.left(90)
sandra.right(90)
alex.forward(347)
sandra.backward(347)
alex.right(210)
sandra.left(210)
alex.forward(102)
sandra.backward(102)

wn.mainloop()